import { useEffect, useState } from "react";
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, TextField } from "@mui/material";
import { createAmcContract } from "../../services/amc.service";
import { getAssets } from "../../services/asset.service";
import { getVendors } from "../../services/vendor.service";

const blank = { contractNumber: "", assetId: "", vendorId: "", startDate: new Date().toISOString().slice(0, 10), expiryDate: "", serviceIntervalMonths: 3, nextServiceDate: "", notes: "" };
export default function AmcDialog({ open, onClose, onSaved }) {
  const [form, setForm] = useState(blank); const [data, setData] = useState({ assets: [], vendors: [] }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!open) return; setForm(blank); setError(""); Promise.all([getAssets(), getVendors()]).then(([assets, vendors]) => setData({ assets: assets.data?.data || [], vendors: vendors || [] })).catch(() => setError("Could not load assets and vendors.")); }, [open]);
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const save = async () => { if (!form.contractNumber || !form.assetId || !form.vendorId || !form.expiryDate) { setError("Complete all required AMC contract fields."); return; } try { setSaving(true); await createAmcContract(form); onSaved(); onClose(); } catch (err) { setError(err.response?.data?.message || "Could not create AMC contract."); } finally { setSaving(false); } };
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><DialogTitle>Add AMC Contract</DialogTitle><DialogContent><Grid container spacing={2} sx={{ mt: 0.25 }}>{error && <Grid item xs={12}><Alert severity="error">{error}</Alert></Grid>}<Grid item xs={12} md={6}><TextField required fullWidth label="AMC contract number" name="contractNumber" value={form.contractNumber} onChange={change} /></Grid><Grid item xs={12} md={6}><TextField required select fullWidth label="Covered asset" name="assetId" value={form.assetId} onChange={change}>{data.assets.map((asset) => <MenuItem key={asset.id} value={asset.id}>{asset.assetCode} - {asset.assetName}</MenuItem>)}</TextField></Grid><Grid item xs={12} md={6}><TextField required select fullWidth label="AMC vendor" name="vendorId" value={form.vendorId} onChange={change}>{data.vendors.map((vendor) => <MenuItem key={vendor.id} value={vendor.id}>{vendor.name}</MenuItem>)}</TextField></Grid><Grid item xs={12} md={6}><TextField required type="number" fullWidth label="Service interval (months)" name="serviceIntervalMonths" inputProps={{ min: 1, max: 24 }} value={form.serviceIntervalMonths} onChange={change} /></Grid><Grid item xs={12} md={4}><TextField required type="date" fullWidth label="Start date" name="startDate" value={form.startDate} onChange={change} InputLabelProps={{ shrink: true }} /></Grid><Grid item xs={12} md={4}><TextField required type="date" fullWidth label="AMC expiry date" name="expiryDate" value={form.expiryDate} onChange={change} InputLabelProps={{ shrink: true }} /></Grid><Grid item xs={12} md={4}><TextField type="date" fullWidth label="Next service due" name="nextServiceDate" value={form.nextServiceDate} onChange={change} helperText="Defaults from start date + interval" InputLabelProps={{ shrink: true }} /></Grid><Grid item xs={12}><TextField fullWidth multiline rows={2} label="Notes" name="notes" value={form.notes} onChange={change} /></Grid></Grid></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={saving} onClick={save}>{saving ? "Saving..." : "Save AMC"}</Button></DialogActions></Dialog>;
}
