import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import SettingsIcon from "@mui/icons-material/Settings";
import PurchaseRequestDialog from "../components/purchaseRequests/PurchaseRequestDialog";
import WorkflowDialog from "../components/purchaseRequests/WorkflowDialog";
import { actionPurchaseRequest, getPurchaseRequests } from "../services/purchaseRequest.service";

const statusColor = { PENDING: "warning", APPROVED: "success", REJECTED: "error" };

export default function PurchaseRequests() {
  const [requests, setRequests] = useState([]); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const [workflowOpen, setWorkflowOpen] = useState(false); const [status, setStatus] = useState("ALL"); const [actionRequest, setActionRequest] = useState(null); const [actorName, setActorName] = useState(""); const [comment, setComment] = useState("");
  const load = async () => { try { setRequests(await getPurchaseRequests()); setError(""); } catch { setError("Unable to load purchase requests."); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => requests.filter((request) => status === "ALL" || request.status === status), [requests, status]);
  const submitAction = async (action) => { try { await actionPurchaseRequest(actionRequest.id, { action, actorName, comment }); setActionRequest(null); setActorName(""); setComment(""); load(); } catch (err) { setError(err.response?.data?.message || "Could not update the approval."); } };
  return <Box p={4}><Typography variant="h4" fontWeight={700} mb={1}>Purchase Requests</Typography><Typography color="text.secondary" mb={3}>Submit department requirements, compare vendor quotations, and follow each approval step.</Typography>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Paper sx={{ p: 2, mb: 3, display: "flex", gap: 2, flexWrap: "wrap", alignItems: "center" }}><TextField select label="Status" value={status} onChange={(e) => setStatus(e.target.value)} sx={{ minWidth: 160 }}><MenuItem value="ALL">All statuses</MenuItem><MenuItem value="PENDING">Pending</MenuItem><MenuItem value="APPROVED">Approved</MenuItem><MenuItem value="REJECTED">Rejected</MenuItem></TextField><Box sx={{ flexGrow: 1 }} /><Button startIcon={<SettingsIcon />} onClick={() => setWorkflowOpen(true)}>Approval workflows</Button><Button variant="contained" startIcon={<AddIcon />} onClick={() => setOpen(true)}>New request</Button></Paper>
    <TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Request</TableCell><TableCell>Department</TableCell><TableCell>Items</TableCell><TableCell>Preferred Vendor</TableCell><TableCell>Estimate</TableCell><TableCell>Approval</TableCell><TableCell>Status</TableCell><TableCell /></TableRow></TableHead><TableBody>{filtered.map((request) => { const steps = request.approvalSteps || []; const nextRole = steps[request.currentApprovalStep]; return <TableRow key={request.id}><TableCell><b>{request.requestNumber}</b><br /><Typography variant="caption">{new Date(request.createdAt).toLocaleDateString()}</Typography></TableCell><TableCell>{request.department?.name}<br /><Typography variant="caption">{request.requestedByName}</Typography></TableCell><TableCell>{request.items.map((item) => `${item.itemDescription} × ${item.quantity}`).join(", ")}</TableCell><TableCell>{request.preferredVendor?.name || "-"}<br />{request.quotations.length ? <Typography variant="caption">{request.quotations.length} quotation(s)</Typography> : null}</TableCell><TableCell>INR {Number(request.estimatedCost).toLocaleString()}</TableCell><TableCell>{request.status === "PENDING" ? `Step ${request.currentApprovalStep + 1}: ${nextRole}` : request.status === "APPROVED" ? "Complete" : "Rejected"}</TableCell><TableCell><Chip size="small" label={request.status} color={statusColor[request.status]} /></TableCell><TableCell>{request.status === "PENDING" && <Button size="small" onClick={() => setActionRequest(request)}>Review</Button>}</TableCell></TableRow>; })}{!filtered.length && <TableRow><TableCell colSpan={8} align="center">No purchase requests found.</TableCell></TableRow>}</TableBody></Table></TableContainer>
    <PurchaseRequestDialog open={open} onClose={() => setOpen(false)} onSaved={load} /><WorkflowDialog open={workflowOpen} onClose={() => setWorkflowOpen(false)} onSaved={() => setWorkflowOpen(false)} />
    <Dialog open={Boolean(actionRequest)} onClose={() => setActionRequest(null)} fullWidth maxWidth="sm"><DialogTitle>Review {actionRequest?.requestNumber}</DialogTitle><DialogContent><Typography sx={{ mb: 2 }}>Current approver: <b>{actionRequest?.approvalSteps?.[actionRequest?.currentApprovalStep]}</b></Typography><TextField autoFocus required fullWidth label="Your name" value={actorName} onChange={(e) => setActorName(e.target.value)} sx={{ mb: 2 }} /><TextField fullWidth multiline rows={3} label="Comment (required for rejection)" value={comment} onChange={(e) => setComment(e.target.value)} /></DialogContent><DialogActions><Button onClick={() => setActionRequest(null)}>Cancel</Button><Button color="error" disabled={!actorName} onClick={() => submitAction("REJECT")}>Reject</Button><Button variant="contained" disabled={!actorName} onClick={() => submitAction("APPROVE")}>Approve step</Button></DialogActions></Dialog>
  </Box>;
}
