import { useEffect, useMemo, useState } from "react";
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, TextField, Typography } from "@mui/material";
import { createInvoice, getInvoiceTaxRules } from "../../services/invoice.service";
import { getDepartments } from "../../services/department.service";
import { getVendors } from "../../services/vendor.service";

const taxLabels = { GST_CGST_SGST: "GST (CGST + SGST) - 18%", IGST: "IGST - 18%", GST_EXEMPT: "GST Exempt - 0%", ZERO_RATED: "Zero Rated (SEZ/Export) - 0%", REVERSE_CHARGE: "Reverse Charge (RCM) - 0%", TDS: "TDS - 10% deduction", TCS: "TCS - 1%", NON_GST: "Non-GST - 0%" };
const paymentLabels = { ADVANCE_100: "100% Advance Payment", ADVANCE_50_COMPLETION_50: "50% Advance & 50% After Completion", CREDIT_15_DAYS: "15 Days Credit", CREDIT_30_DAYS: "30 Days Credit", DUE_ON_RECEIPT: "Due Upon Receipt" };
const empty = { vendorId: "", departmentId: "", invoiceNumber: "", invoiceDate: new Date().toISOString().slice(0, 10), paymentTerm: "CREDIT_30_DAYS", taxType: "GST_CGST_SGST", subtotalAmount: "", notes: "" };

export default function InvoiceDialog({ open, onClose, onSaved }) {
  const [form, setForm] = useState(empty); const [file, setFile] = useState(null); const [data, setData] = useState({ vendors: [], departments: [], rules: null }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!open) return; setForm(empty); setFile(null); setError(""); Promise.all([getVendors(), getDepartments(), getInvoiceTaxRules()]).then(([vendors, departments, rules]) => setData({ vendors: vendors || [], departments: departments.data?.data || [], rules })).catch(() => setError("Could not load invoice form options.")); }, [open]);
  const calculation = useMemo(() => { const subtotal = Number(form.subtotalAmount) || 0; const rate = data.rules?.taxRates?.[form.taxType] || 0; const tax = subtotal * rate / 100; const due = new Date(`${form.invoiceDate}T00:00:00`); due.setDate(due.getDate() + (data.rules?.paymentTermDays?.[form.paymentTerm] || 0)); return { rate, tax, total: subtotal + tax, due }; }, [form, data.rules]);
  const save = async () => { if (!form.vendorId || !form.invoiceNumber || !form.invoiceDate || !Number(form.subtotalAmount)) { setError("Complete all required invoice details."); return; } try { setSaving(true); await createInvoice(form, file); onSaved(); onClose(); } catch (err) { setError(err.response?.data?.message || "Could not upload invoice."); } finally { setSaving(false); } };
  const change = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><DialogTitle>Upload Vendor Invoice</DialogTitle><DialogContent><Grid container spacing={2} sx={{ mt: 0.25 }}>{error && <Grid item xs={12}><Alert severity="error">{error}</Alert></Grid>}<Grid item xs={12} md={6}><TextField required select fullWidth label="Vendor" name="vendorId" value={form.vendorId} onChange={change}>{data.vendors.map((vendor) => <MenuItem key={vendor.id} value={vendor.id}>{vendor.name}</MenuItem>)}</TextField></Grid><Grid item xs={12} md={6}><TextField select fullWidth label="Notify department" name="departmentId" value={form.departmentId} onChange={change}><MenuItem value="">Finance only</MenuItem>{data.departments.map((department) => <MenuItem key={department.id} value={department.id}>{department.name}</MenuItem>)}</TextField></Grid><Grid item xs={12} md={4}><TextField required fullWidth label="Invoice number" name="invoiceNumber" value={form.invoiceNumber} onChange={change} /></Grid><Grid item xs={12} md={4}><TextField required fullWidth type="date" label="Invoice date" name="invoiceDate" value={form.invoiceDate} onChange={change} InputLabelProps={{ shrink: true }} /></Grid><Grid item xs={12} md={4}><TextField required fullWidth type="number" inputProps={{ min: 0.01, step: "0.01" }} label="Subtotal amount (INR)" name="subtotalAmount" value={form.subtotalAmount} onChange={change} /></Grid><Grid item xs={12} md={6}><TextField select fullWidth label="Payment terms" name="paymentTerm" value={form.paymentTerm} onChange={change}>{Object.entries(paymentLabels).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField></Grid><Grid item xs={12} md={6}><TextField select fullWidth label="Tax type" name="taxType" value={form.taxType} onChange={change}>{Object.entries(taxLabels).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField></Grid><Grid item xs={12}><Alert severity="info">Tax ({calculation.rate}%): INR {calculation.tax.toLocaleString(undefined, { maximumFractionDigits: 2 })} | Total: INR {calculation.total.toLocaleString(undefined, { maximumFractionDigits: 2 })} | Due: {calculation.due.toLocaleDateString()}</Alert></Grid><Grid item xs={12}><Button component="label" variant="outlined">Attach invoice (PDF, JPG, or PNG)<input hidden type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={(e) => setFile(e.target.files?.[0] || null)} /></Button>{file && <Typography variant="body2" sx={{ mt: 1 }}>{file.name}</Typography>}</Grid><Grid item xs={12}><TextField fullWidth multiline rows={2} label="Notes" name="notes" value={form.notes} onChange={change} /></Grid></Grid></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={saving} onClick={save}>{saving ? "Uploading..." : "Save Invoice"}</Button></DialogActions></Dialog>;
}
